name: Sync and Merge Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Sync with upstream
        run: git remote add upstream https://github.com/AscensionGameDev/Intersect-Engine.git && git fetch upstream && git checkout main && git merge upstream/main

      - name: Merge dev into main
        run: |
          git checkout main
          git merge origin/dev --no-ff --no-commit
          git checkout -- .

      - name: Keep images from dev branch
        run: |
          git checkout dev -- '*.png' '*.ico' '*.bmp' '*.svg'
          git add .
          git commit -m "Merge dev into main keeping images"

      - name: Push changes to release branch
        run: |
          git push origin main
          git checkout -b release
          git push origin release
